<?php

/*
 * The MIT License
 *
 * Copyright 2022 zozlak.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

namespace aksearchExt\container;

use SimpleXMLElement;
use VuFind\I18n\TranslatableString;
use aksearchExt\Alma;

/**
 * A container for the holding item description
 *
 * @author zozlak
 */
class ItemData {

    static public function fromAve(object $ave): self {
        $data = new ItemData();
        $data->availability = true;
        $data->url = $ave->x;
        $data->mmsId = $ave->{0};
        $data->description = $ave->P;
        $data->status = $ave->b;
/*    
|a 5323347380004498
|b Available
"e Available
|c static
|d https://obv-at-oeaw.userservices.exlibrisgroup.com/view/uresolver/43ACC_OEAW/openurl?u.ignore_date_coverage=true&rft.mms_id=990002108420504498
[e_url https://eu02.alma.exlibrisgroup.com/view/uresolver/43ACC_OEAW/openurl?u.ignore_date_coverage=true&portfolio_pid=5323347380004498&Force_direct=true
|e JOURNAL
|h false
|o 6127389660004498
"c 6127389660004498
|P Open Access EJournal Verlag der Österreichischen Akademie der Wissenschaften
"m Open Access EJournal Verlag der Österreichischen Akademie der Wissenschaften
[location Open Access EJournal Verlag der Österreichischen Akademie der Wissenschaften
|u 2019-03-22 15:11:54 Europe/Vienna
|v 2022-02-16 16:42:23 Europe/Vienna
|w 2019-03-22 15:41:23
|x https://eu02.alma.exlibrisgroup.com/view/uresolver/43ACC_OEAW/openurl?u.ignore_date_coverage=true&portfolio_pid=5323347380004498&Force_direct=true
|0 6227389650004498
"0 990002108420504498
[id 990002108420504498
|8 5323347380004498
"8 5323347380004498
*/
        return $data;
    }
    
    static public function fromAlma(SimpleXMLElement $item): self {
        $data = new ItemData();
        $status  = (string) $item->item_data->base_status[0]->attributes()['desc'];
        $duedate = $item->item_data->due_date ? Alma::parseDateStatic((string) $item->item_data->due_date) : null;
        if ($duedate && 'Item not in place' === $status) {
            $status = 'Checked Out';
        }

        $processType = (string) ($item->item_data->process_type ?? '');
        if (!empty($processType) && 'LOAN' !== $processType) {
            $status = $item->item_data->process_type;
        }

        $data->mmsId        = (int) $item->bib_data->mms_id;
        $data->holdingId    = (int) $item->holding_data->holding_id;
        $data->itemId       = (int) $item->item_data->pid;
        $data->availability = ((string) $item->item_data->base_status) === '1';
        $data->status       = $status;
        $data->location     = (string) $item->item_data->location;
        $data->callNumber   = (string) $item->holding_data->call_number;
        $data->callNumber2  = (string) $item->holding_data->alternative_call_number;
        $data->duedate      = $duedate;
        $data->notes        = (string) $item->item_data->public_note;
        $data->description  = (string) $item->item_data->description;
        $data->policy       = (string) $item->item_data->policy;
        return $data;        
    }
    
    public int $mmsId;
    public int $holdingId;
    public int $itemId;
    public bool $availability;
    public string $status = '';
    public string $location = '';
    public string $callNumber = '';
    public string $callNumber2 = '';
    public ?string $duedate = null;
    public string $notes = '';
    public string $description = '';
    public string $policy = '';
    public string $url = '';

    /**
     * Generated by VuFind\ILS\Logic::getRequestDetails()
     * 
     * @var array<string>
     */
    public ?array $link = null;

    public function asVuFindArray(): array {
        return [
            'id'          => $this->mmsId,
            'holding_id'  => $this->holdingId,
            'item_id'     => $this->itemId,
            'location'    => $this->location,
            'callnumber'  => $this->callNumber,
            'description' => $this->description,
            'item_notes'  => $this->notes,
            'policy'      => $this->policy,
        ];
    }
}
